import { readFileSync, writeFileSync } from "node:fs";
import { applyGrowth, DEFAULT_TUNING, GROWTH_STEPS } from "../client/src/pages/village-map-demo/catalog";
import {
  containSlots,
  layoutWallRadius,
  placedSlots,
  wallStrokeWidth,
  type Point,
} from "../client/src/pages/village-map-demo/geometry";

const overridesPath = process.argv[2];
const dragged: Record<string, Point> = overridesPath
  ? JSON.parse(readFileSync(overridesPath, "utf8"))
  : {};

const tuning = DEFAULT_TUNING;
const build = applyGrowth(GROWTH_STEPS.length);
const radius = layoutWallRadius(tuning);
const thickness = wallStrokeWidth(build.wall, tuning.wallThickness);
const slots = containSlots(placedSlots(build, tuning, dragged), radius, tuning, thickness, build.wall);
const again = containSlots(
  placedSlots(
    build,
    tuning,
    Object.fromEntries(slots.map((slot) => [slot.id, { x: slot.x, y: slot.y }])),
  ),
  radius,
  tuning,
  thickness,
  build.wall,
);
let drift = 0;
for (const slot of slots) {
  const next = again.find((item) => item.id === slot.id);
  if (!next) throw new Error(`missing ${slot.id}`);
  drift = Math.max(drift, Math.hypot(next.x - slot.x, next.y - slot.y));
}
if (drift > 1e-6) {
  throw new Error(`contained positions drift by ${drift} when reused as overrides`);
}

const lines = slots.map(
  (slot) => `  "${slot.id}": { x: ${Math.round(slot.x)}, y: ${Math.round(slot.y)} },`,
);
const source = overridesPath
  ? "the village-map demo arrangement"
  : "the unmoved full-village layout";
const file = `/** Full-village map positions, frozen for the game. Generated by scripts/export-village-map-layout.ts from ${source}. */
export const VILLAGE_MAP_POSITIONS: Record<string, { x: number; y: number }> = {
${lines.join("\n")}
};
`;
writeFileSync(new URL("../client/src/game/villageMapLayout.ts", import.meta.url), file);
console.log(`wrote ${slots.length} positions from ${source}, drift ${drift}`);
