import { readFileSync, writeFileSync } from "node:fs";
import { applyGrowth, DEFAULT_TUNING, GROWTH_STEPS } from "../client/src/pages/village-map-demo/catalog";
import {
  containSlots,
  layoutWallRadius,
  placedSlots,
  wallStrokeWidth,
  type Point,
} from "../client/src/pages/village-map-demo/geometry";

type MapTree = { id: string; variant: string; x: number; y: number; turn: number };

const overridesPath = process.argv[2];
const raw: {
  overrides?: Record<string, Point>;
  pathOverrides?: Record<string, Point>;
  trees?: MapTree[];
} & Record<string, Point> = overridesPath ? JSON.parse(readFileSync(overridesPath, "utf8")) : {};
const dragged: Record<string, Point> =
  raw.overrides ??
  Object.fromEntries(Object.entries(raw).filter(([, point]) => typeof point?.x === "number"));
const includePaths = Object.prototype.hasOwnProperty.call(raw, "pathOverrides");
const includeTrees = Object.prototype.hasOwnProperty.call(raw, "trees");
const pathOverrides = raw.pathOverrides ?? {};
const trees = raw.trees ?? [];

const tuning = DEFAULT_TUNING;
const build = applyGrowth(GROWTH_STEPS.length);
const radius = layoutWallRadius(tuning);
const thickness = wallStrokeWidth(build.wall, tuning.wallThickness);
const slots = containSlots(placedSlots(build, tuning, dragged), radius, tuning, thickness, build.wall);
const again = containSlots(
  placedSlots(
    build,
    tuning,
    Object.fromEntries(slots.map((slot) => [slot.id, { x: slot.x, y: slot.y }])),
  ),
  radius,
  tuning,
  thickness,
  build.wall,
);
let drift = 0;
for (const slot of slots) {
  const next = again.find((item) => item.id === slot.id);
  if (!next) throw new Error(`missing ${slot.id}`);
  drift = Math.max(drift, Math.hypot(next.x - slot.x, next.y - slot.y));
}
if (drift > 1e-6) {
  throw new Error(`contained positions drift by ${drift} when reused as overrides`);
}

const lines = slots.map(
  (slot) => `  "${slot.id}": { x: ${Math.round(slot.x)}, y: ${Math.round(slot.y)} },`,
);
const layoutUrl = new URL("../client/src/game/villageMapLayout.ts", import.meta.url);
const previous = readFileSync(layoutUrl, "utf8");
const kept = (name: string) => {
  const start = previous.indexOf(`export const ${name}`);
  if (start < 0) return "";
  const next = previous.indexOf("\nexport const ", start + 1);
  return previous.slice(start, next < 0 ? undefined : next).trimEnd();
};
const pathBlock = includePaths
  ? `/** Road bends from the same arrangement. A handle sits on the named path. */
export const VILLAGE_MAP_PATH_OVERRIDES: Record<string, { x: number; y: number }> = {
${Object.entries(pathOverrides)
    .map(([id, point]) => `  "${id}": { x: ${Math.round(point.x)}, y: ${Math.round(point.y)} },`)
    .join("\n")}
};`
  : kept("VILLAGE_MAP_PATH_OVERRIDES");
const treeBlock = includeTrees
  ? `/** Crowns from the same arrangement. */
export const VILLAGE_MAP_TREES: { id: string; variant: string; x: number; y: number; turn: number }[] = [
${trees
    .map(
      (tree) =>
        `  { id: "${tree.id}", variant: "${tree.variant}", x: ${Math.round(tree.x)}, y: ${Math.round(tree.y)}, turn: ${Math.round(tree.turn)} },`,
    )
    .join("\n")}
];`
  : kept("VILLAGE_MAP_TREES");
const source = overridesPath
  ? "the village-map demo arrangement"
  : "the unmoved full-village layout";
const file = [
  `/** Full-village map positions, road bends, and trees, frozen for the game. Generated by scripts/export-village-map-layout.ts from ${source}. */
export const VILLAGE_MAP_POSITIONS: Record<string, { x: number; y: number }> = {
${lines.join("\n")}
};`,
  pathBlock,
  treeBlock,
]
  .filter((part) => part.length > 0)
  .join("\n\n")
  .concat("\n");
writeFileSync(layoutUrl, file);
console.log(
  `wrote ${slots.length} positions, ${includePaths ? Object.keys(pathOverrides).length : "kept"} path bends, ${includeTrees ? trees.length : "kept"} trees from ${source}, drift ${drift}`,
);
